### ISSUE TITLE
Error: Cannot find module '../../@config'

### ISSUE THREAD

**Issue by P1AME** [localip/telegram-to-discord#1]
root@debian-valo-grade:~/telegram-to-discord# npm run build

> telegram-to-discord@1.0.0 build /root/telegram-to-discord
> swc src -d dist -D --delete-dir-on-start

Successfully compiled: 13 files with swc (89.71ms)
root@debian-valo-grade:~/telegram-to-discord# npm run start

> telegram-to-discord@1.0.0 start /root/telegram-to-discord
> node dist/index.js

internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module '../../@config'

**Comment by localip** [comment]
Hey, please ensure config.json exists at the root of the project. You may rename sample_config.json to config.json and configure it from there.

**Comment by P1AME** [comment]
Hey,
Thank you for your fast answer.

The file config.json does exists and I copied sample_config.json as config.json to configure it.

**Comment by localip** [comment]
Unfortunately this seems like a @swc/core issue. A temporary fix is to replace the path aliases and have them start with "~/*" instead of "@*".

**Comment by localip** [comment]
@swc-project Could you have a look at the above? This repo should be enough for reproduction.
